### ISSUE TITLE
Extending to Logistic Regression

### ISSUE THREAD

**Issue by sandy9999** [mkskeller/mnist-mpc#1]
I'm looking to run `mnist_logreg.mpc` instead of `mnist_full_A.mpc`. I noticed that the program arguments are more or less same, I pass parameters such that `mnist_logreg-20-128-1-approx-trunc_pr-1dense-always_acc` is passed to `mnist_logreg.mpc`. I know this has extraneous parameters for logistic regression, but from what I observed from the `.mpc` file and `ml.py` these extraneous parameters will anyway be ignored.

I did this by changing line 49 of `common.sh` to `args="mnist_full_A $n_epochs 128 $n_threads $args"`

On building the docker image, this is the log I obtain

```sh
Doing Player-Data

Purging preprocessed data because something is wrong
terminate called after throwing an instance of 'IO_Error'
  what():  IO-Error : cannot read integer from Player-Data/Input-P0-0, problem with '.0'
Purging preprocessed data because something is wrong
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  read_some: stream truncated
Purging preprocessed data because something is wrong
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  read_some: stream truncated
bash: line 3:   239 Aborted                 (core dumped) static/replicated-ring-party.x mnist_logreg-1-128-1-approx-nearest-split3-1dense-always_acc -h 127.0.0.1 -pn 23786 -p 0
bash: line 3:   236 Aborted                 (core dumped) static/replicated-ring-party.x mnist_logreg-1-128-1-approx-nearest-split3-1dense-always_acc -h 127.0.0.1 -pn 23786 -p 1
bash: line 3:   266 Aborted                 (core dumped) static/replicated-ring-party.x mnist_logreg-1-128-1-approx-nearest-split3-1dense-always_acc -h 127.0.0.1 -pn 23786 -p 2
```

What else should I look into to get Logistic Regression to run correctly. I also understand that Logistic Regression uses the 0 and 1 labels from the MNIST dataset and performs binary classification.

**Comment by mkskeller** [comment]
You need to use full01.py which I've just added) instead of full.py.

**Comment by sandy9999** [comment]
Thank you! This helped.
